name: SkywarsOlymp
version: ${project.version}
main: com.monsbot.skywarsolymp.SkywarsOlymp
description: Skywars plugin Olympmc
author: Monsbot
website: OlympMc.net

commands:
  debugSw:
    description: Just debug stuff. §c§o(Don't use high numbers)